# Generated by Django 4.2.3 on 2024-11-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tags',
            field=models.JSONField(blank=True, help_text='Provide tags in JSON format', null=True),
        ),
    ]
